### ISSUE TITLE
【instagram代码报错】:TypeError: exceptions must derive from BaseException

### ISSUE THREAD

**Issue by Qzy568** [xishandong/crawlProject#18]
【instagram代码报错】：file_path：crawlProject/进阶篇/基础综合/Instagram/downloader.py
Traceback (most recent call last):
  File "/Users/qiaozheyu/Code/crawlProject/进阶篇/基础综合/Instagram/downloader.py", line 87, in get_userInfo
    data = resp['data']['user']
           ~~~~^^^^^^^^
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/qiaozheyu/Code/crawlProject/进阶篇/基础综合/Instagram/downloader.py", line 235, in <module>
    item = INS.get_userInfo('renebaebae')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qiaozheyu/Code/crawlProject/进阶篇/基础综合/Instagram/downloader.py", line 89, in get_userInfo
    raise 'Could not get user information...'
TypeError: exceptions must derive from BaseException

**Comment by xishandong** [comment]
已修复
